### PR TITLE
Responsive Design

### PR DESCRIPTION
**Pull request by frankopkusianwar**
#### What does this PR do?

- Shows a responsive design of the next web page clone

### Description of Task to be completed?

 - Added the HTML index file
 - Added CSS to style and layout the page. 
- Add media queries in CSS file to make the page responsive
 - Ran validations on our Html and CSS. 

#### How should this be manually tested? 

- Clone this branch. 
- open the index.html file on your browser

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @frankopkusianwar and @OA7 
### You guys have done a great job so far :clap: However, you have an issue to solve before your application can be approved.
- On mobile and medium screen sizes, your hero section is not designed as per the [reference website](https://thenextweb.com/)
### Your design
yours
### Expected Design
expectation
### Make this change and resubmit for another code review. Good luck.
- Happy coding!

**Comment by uryelah** [comment]
Hello **Osong Agberndifor** & **Frank Okiror**, I'm Sarah, your reviewer for this PR 👩‍🚀  

It seems that you might have missed the requirement from the last TSE.
The issue is that a lot of the small text with the author of the article, date, and share icon that is present under the titles in the [original site](https://thenextweb.com/) is nowhere to be seen in your clone. 

Please read carefully the required changes bellow and compare your clone with the [original site](https://thenextweb.com/) once again.

---------    

### Required changes 🛠 
---------

- [ ] The top articles should be aligned. Compare your version and the original site bellow and fix it on big and medium sizes.

**Your version**
Screenshot_2020-03-18 Responsive Design
**Original site**
Screenshot_2020-03-18 TNW - International technology news, business and culture


- [ ] The pink/orange gradient is only present over the first main article at big screens. 
Yours is visible even on small screens. 

- [ ] Most of the articles, but the 'Lastest deals' ones, have some text or images missing from them. Please use the images below as a reference and compare again your clone with the original site.
**Your version**
Screenshot_2020-03-18 Responsive Design(1)
**Original version**
Screenshot_2020-03-18 TNW - International technology news, business and culture(1)
-----
**Your version**
Screenshot_2020-03-18 Responsive Design(2)
**Original version**
Screenshot_2020-03-18 TNW - International technology news, business and culture(2)

----------
## Optional Improvements

- [ ] [OPTIONAL] The color of the yellow `.navbar_text` at the top is wrong. Tip: Use a color picker, as firefox has in its devtools, to get the exact color.

- [ ] [OPTIONAL] Same as above but for the `.top-container__main` gradient color.
--------

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Comment by nikasulo** [comment]
# Great work @frankopkusianwar and @OA7 :clap: 
Please consider my comments below, make the necessary changes and request another review. I wish you the very best!

#### Horizontal scroLloyd
Please note that your page currently has a bug causing it to scroll horizontally, kindly look into this and make the required adjustments. 

#### Latest Funding section 
Please note that the images on each card in the section are missing. Kindly look into this :handshake: 

#### Responsiveness 
I'd also like to bring to your attention that your project isn't as responsive as it should be, please consider assessing your project on at least these two screen sizes; 320px and 768px, comparing each section closely with the counterpart in the original site.

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on Twitter or Instagram, even if you just want to chat and I will respond to you as soon as I can.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @frankopkusianwar, congratulations on a wonderful work done 👌 The project is now responsive, horizontal scroll removed, main content responsive. 🙂 Let us improve the project a bit since our main focus is on how content behaves on different screen sizes. Kindly check the comments below:
* Latest deals is missing ```see all deals``` text. Let us add it. Currently this is how it looks on ```small screen```
lap1
```Original```
lap
* Let us address this, the ```original``` has ```header```  ```description``` ```timestamp```. Currently, we are missing the ```header``` as in the images below. Also the position of the text
lap2
```Original```
lap3
```Medium screen```
Currently,
lap6
```Original```
lap7
* Let us improve our CSS file, we can refactor the code to avoid DRY and also consider the mobile-first approach. Meaning we should have 2 media queries, which are 768px and 1024px. Currently, we have 5 media queries

Kindly make these changes and submit another code review 🙂 
See you at the top 🚀 
_Happy coding_ 👨‍💻 
You can find me on slack => Daniel Larbi Addo

**Review by rOluochKe — APPROVED** [review]
Hello Team
### After making changes from previous reviews, the project looks good. Congratulations :boom: :100: your project has been approved.
### You can merge and submit from your dashboard. Good luck with the next project.
- Happy coding!

**Pull request merged**
